version: '3.8'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./src/rest
          target: /src/rest
    

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && ls && yarn install && yarn start"
    ports:
      - "3000:3000"

    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /src/app

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0